# Generated by Django 5.2.17 on 2026-09-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Başlık')),
                ('slug', models.SlugField(unique=True, verbose_name='Adres kısa adı')),
                ('author_name', models.CharField(max_length=150, verbose_name='Yazar adı')),
                ('summary', models.TextField(blank=True, verbose_name='Kısa açıklama')),
                ('content', models.TextField(verbose_name='Yazı metni')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='Kapak görseli')),
                ('section', models.CharField(choices=[('dosya', 'Dosya'), ('ceviri', 'Çeviri'), ('tartisma', 'Tartışma ve Yorum')], default='dosya', max_length=20, verbose_name='Bölüm')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında')], default='draft', max_length=20, verbose_name='Yayın durumu')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Manşette göster')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma zamanı')),
            ],
            options={
                'verbose_name': 'Yazı',
                'verbose_name_plural': 'Yazılar',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
