# Generated by Django 5.2.17 on 2026-09-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kavram')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sitede göster')),
            ],
            options={
                'verbose_name': 'Kavram',
                'verbose_name_plural': 'Kavramlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='is_archive_pick',
            field=models.BooleanField(default=False, verbose_name='Arşivden seçmelerde göster'),
        ),
    ]
