# Generated by Django 5.2.17 on 2026-09-15 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_concept_article_is_archive_pick'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=20, verbose_name='Platform')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Kısa açıklama')),
                ('image', models.ImageField(blank=True, upload_to='social/', verbose_name='Görsel')),
                ('url', models.URLField(help_text='Gönderinin veya videonun tam bağlantısını gir.', max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='Gönderi bağlantısı')),
                ('order', models.PositiveIntegerField(default=0, help_text='Küçük sayılar önce gösterilir.', verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sitede göster')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme zamanı')),
            ],
            options={
                'verbose_name': 'Sosyal medya gönderisi',
                'verbose_name_plural': 'Sosyal medya gönderileri',
                'ordering': ['order', '-created_at', '-id'],
            },
        ),
    ]
