# Generated by Django 5.2.17 on 2026-09-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_socialpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Yayındaki yazıda boş bırakılırsa kaydedildiği zaman kullanılır.', null=True, verbose_name='Yayın tarihi'),
        ),
    ]
