# Generated by Django 5.2.17 on 2026-09-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='Biçimlendirilmiş yazı'),
        ),
    ]
