# Generated by Django 5.2.17 on 2026-09-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_content_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dosya başlığı')),
                ('slug', models.SlugField(help_text='Örnek: emek', max_length=220, unique=True, verbose_name='Adres kısa adı')),
                ('summary', models.TextField(blank=True, help_text='Dosya kartlarında gösterilecek kısa açıklama.', verbose_name='Kısa açıklama')),
                ('description', models.TextField(blank=True, help_text='Dosya sayfasının üst bölümünde gösterilir.', verbose_name='Dosya tanıtım metni')),
                ('cover', models.ImageField(blank=True, upload_to='dossiers/', verbose_name='Dosya kapak görseli')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında')], default='draft', max_length=20, verbose_name='Yayın durumu')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Ana sayfada göster')),
                ('order', models.PositiveIntegerField(default=0, help_text='Küçük sayılar önce gösterilir.', verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma zamanı')),
                ('published_at', models.DateTimeField(blank=True, help_text='Yayındaki dosyada boş bırakılırsa kaydedildiği zaman kullanılır.', null=True, verbose_name='Yayın tarihi')),
            ],
            options={
                'verbose_name': 'Dosya',
                'verbose_name_plural': 'Dosyalar',
                'ordering': ['order', '-published_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='dossier_order',
            field=models.PositiveIntegerField(default=0, help_text='Dosya sayfasındaki sıralamayı belirler. Küçük sayılar önce gösterilir.', verbose_name='Dosya içindeki sıralama'),
        ),
        migrations.AddField(
            model_name='article',
            name='dossier',
            field=models.ForeignKey(blank=True, help_text='Yazı bir tematik dosyaya aitse seçin. Örnek: Emek.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.dossier', verbose_name='Bağlı olduğu dosya'),
        ),
    ]
