# Generated by Django 5.2.17 on 2026-10-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_dossier_article_dossier_order_article_dossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(unique=True, verbose_name='Adres kısa adı')),
                ('intro', models.TextField(blank=True, verbose_name='Giriş metni')),
                ('content', models.TextField(blank=True, help_text='Paragrafları boş satırla ayırın.', verbose_name='Sayfa metni')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Menü sırası')),
            ],
            options={
                'verbose_name': 'Kurumsal sayfa',
                'verbose_name_plural': 'Kurumsal sayfalar',
                'ordering': ['order', 'title'],
            },
        ),
    ]
