# Generated by Django 5.2.17 on 2026-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_institutional_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('dosya', 'Dosya'), ('ceviri', 'Çeviri'), ('tartisma', 'Tartışma')], default='dosya', max_length=20, verbose_name='Bölüm'),
        ),
    ]
